### ISSUE TITLE
Tests failing due to ZIP file not being extracted

### ISSUE THREAD

**Issue by jonschumacher** [MagneticParticleImaging/MPIReco.jl#12]
When I try to run the tests for MPIReco, I get the following error:

> [ Info: download data.zip
> 
> [ Info: extracting data.zip
> ERROR: LoadError: IOError: could not spawn `unzip -oq data.zip`: no such file or directory (ENOENT)
> Stacktrace:
>  [1] _spawn_primitive(::String, ::Cmd, ::Array{Any,1}) at ./process.jl:99
>  [2] #550 at ./process.jl:112 [inlined]
>  [3] setup_stdios(::Base.var"#550#551"{Cmd}, ::Array{Any,1}) at ./process.jl:196
>  [4] _spawn at ./process.jl:111 [inlined]
>  [5] run(::Cmd; wait::Bool) at ./process.jl:439
>  [6] run(::Cmd) at ./process.jl:438
>  [7] top-level scope at /home/schumacherj/.julia/packages/MPIReco/CL5HV/test/runtests.jl:14
>  [8] include(::String) at ./client.jl:439
>  [9] top-level scope at none:6
> in expression starting at /home/schumacherj/.julia/packages/MPIReco/CL5HV/test/runtests.jl:6
> ERROR: Package MPIReco errored during testing

This happens on both Windows and Ubuntu within WSL.
I will try to fix it myself and create a PR, but wanted to mention it here for others wondering about the error aswell (e.g. our HiWi ;)).

**Comment by tknopp** [comment]
Of course MPIReco is supposed to work on Windows as well but it might be that we run the tests just on Linux since `unzip` is not available in this environoment.

**Comment by tknopp** [comment]
your fix looks fine to me. I just wanted to suggest to use `ZipFile.jl` but I agree with your judgement in the comment. In the future I actually want to switch to Julias binary packages but had not time to figure out how they exactly work.

**Comment by tknopp** [comment]
#8 is actually what I was talking about

**Comment by sanojb** [comment]
Looks interesting, but this seems to be around for quite a while. For now, we could go with my fix and implement it later. Should I open a PR?

**Comment by jonschumacher** [comment]
Looks like the tar.gz version is the way to go. It doesn't need ZIP file support in Julia and works out-of-the box with artifacts. If you would consider hosting the data as a tarball, I could implement a version and send you a link to the repackaged data file.
