### ISSUE TITLE
Plotting with WInston not working under Julia 1.0.0

### ISSUE THREAD

**Issue by hofmannmartin** [MagneticParticleImaging/MPIReco.jl#2]
Should we try out `ImageView` instead of `Winston`? Will likely always work work with our `Image` objects.

**Comment by tknopp** [comment]
What does Not Work exactly? When you include "runtests.jl" manually it should work. I have ported Winston to 1.0 and thought that it is working. Maybe the Winston Version neads to be updated.

**Comment by tknopp** [comment]
I made a commit that saves the figures into pngs (still using Winston). Better would be to use our `exportImage` routines from `MPILib`. But this will require moving them to a standalone package (including the coloring code). Not 100% sure how this will look like.
