### ISSUE TITLE
Type piracy breaking incremental compilation

### ISSUE THREAD

**Issue by jonschumacher** [MagneticParticleImaging/MPIReco.jl#20]
`using MPIReco` gives the following output:

```julia
WARNING: Method definition has_args5(LinearOperators.opEye) in module SparsityOperators at /home/schumacherj/.julia/packages/SparsityOperators/uMtMk/src/SparsityOperators.jl:18 overwritten in module LinearOperatorCollection at /home/schumacherj/.julia/packages/LinearOperatorCollection/SvtgC/src/LinearOperatorCollection.jl:16.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition use_prod5!(LinearOperators.opEye) in module SparsityOperators at /home/schumacherj/.julia/packages/SparsityOperators/uMtMk/src/SparsityOperators.jl:17 overwritten in module LinearOperatorCollection at /home/schumacherj/.julia/packages/LinearOperatorCollection/SvtgC/src/LinearOperatorCollection.jl:15.
  ** incremental compilation may be fatally broken for this module **
``` 

This happens due to both `LinearOperatorCollection` (used in `MPIFiles`) and `SparsityOperators` (used in `RegularizedLeastSquares`) both defining

```julia
LinearOperators.use_prod5!(op::opEye) = false
LinearOperators.has_args5(op::opEye) = false
``` 

in their main files, which is a type piracy (https://github.com/JuliaImageRecon/LinearOperatorCollection.jl/blob/5d2fe7d9d70e1badb57dd74aced22355beb423ee/src/LinearOperatorCollection.jl#L14C1-L16C45 und https://github.com/JuliaImageRecon/LinearOperatorCollection.jl/blob/5d2fe7d9d70e1badb57dd74aced22355beb423ee/src/LinearOperatorCollection.jl#L15C1-L16C45).

Since I am not sure why these methods are definied in the respective packages, I can only leave this issue here and can't provide a PR.

**Comment by tknopp** [comment]
MPIReco ist currently broken because of the recent MPIFiles releases. @nHackel ist currently working in a fix, which ist already on a branch and needs backporting.

**Comment by jonschumacher** [comment]
Seems to work again. I will close here.
