### ISSUE TITLE
removed shape parameter in low level reconstruction

### ISSUE THREAD

**Issue by floriangriese** [MagneticParticleImaging/MPIReco.jl#5]
’"""
Low level reconstruction method
"""
function reconstruction(S, u::Array; sparseTrafo = nothing,
                        lambd=0.0, lambda=lambd, λ=lambda, progress=nothing, solver = "kaczmarz",
weights=nothing, enforceReal=true, enforcePositive=true, kargs...)`

@tknopp The results are returned in format (x,y,z,color,t) which is not documented as far as I know. I would prefer an overloaded reconstruction with shape parameter in the low level reconstruction.

**Comment by tknopp** [comment]
I have discussed this with Patryk (and removed the shape afterwards). The point is that you can have something like
```
  reshapetoimage( reconstruction(S,u) shape)
``` 
instead of
```
  reconstruction(S,u, shape)
```
The former version is type stable, while the later is not.

The low-level reconstruction has the format (N,L) where L is the number of frames and N=color*Nx*Ny*Nz.

**Comment by tknopp** [comment]
(reshapetoimage is a hypothetical function, I have not implemented it yet, since there seemed to be no use case for it)

**Comment by tknopp** [comment]
closing this since this is currently no issue.
