### ISSUE TITLE
Consider using Artifacts for test data

### ISSUE THREAD

**Issue by vchuravy** [MagneticParticleImaging/MPIReco.jl#7]
https://github.com/MagneticParticleImaging/MPIReco.jl/blob/1642d60277b4965010c4c421aa9c7662ac693a8c/test/runtests.jl#L8

Currently every run of PackageEvaluator.jl and likely travis will download the 2.7GB test file from tuhh.de, if you Artifacts PackageEvaluator can cache the data and that will make it also easier for you to cache the data on Travis.

**Comment by tknopp** [comment]
Yes indeed that would be nice. Could you point me to an example where this is in use? I tried reading docus on artifacts but they were mostly BB related.

**Comment by tknopp** [comment]
Ah, and this data should only be downloaded when running the test, not when installing the package.

**Comment by vchuravy** [comment]
https://julialang.github.io/Pkg.jl/v1/artifacts/#Using-Artifacts-1

Has an Iris dataset example, and I think you can get the behaviour you want by using `lazy=true` in the Artifact

**Comment by tknopp** [comment]
thanks, I will have a look at this once I find time.
